spring:
  application.name: stackthon
  main.allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 1qazxsw2
    name: fsnre
    maxActive: 20
    initialSize: 1
    maxWait: 60000

mybatis:
  mapper-locations: mapper/*.xml
  configuration.map-underscore-to-camel-case: true
server:
  port: 8082
mapper:
  not-empty: false
  identity: MYSQL
#spring.servlet.multipart.maxFileSize=50MB
#spring.servlet.multipart.maxRequestSize=100MB
oauth.security.sign-key: 1zaGEyLW5pc3RwNTIxAAAACG5pc3RwNTIxAAAAhQQBTiaqM1Ydq4UPGgPAd6LcWFG5YKPn
swagger.enable: true